[build]
base = "pansift"
publish = "pansift/public"
command = "hugo --enableGitInfo"

# Old HUGO working version "0.47.1"

[context.production.environment]
HUGO_VERSION = "0.86.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.86.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.86.0"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.86.0"
HUGO_ENABLEGITINFO = "true"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/plugins/themefisher-font/fonts/*.woff|/plugins/themefisher-font/fonts/*.ttf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"

[[redirects]]
  from = "/byloggingin"
  to = "https://app.pansift.com"
  force = true

[[redirects]]
  from = "https://blog.pansift.com"
  to = "https://pansift.com/blog"
  force = true

[[redirects]]
  from = "https://ingest4.pansift.com"
  to = "https://pansift.com"
  force = true

[[redirects]]
  from = "https://ingest-default.pansift.com"
  to = "https://pansift.com"
  force = true

[[redirects]]
  from = "/demo"
  to = "https://app.pansift.com/demo?first_insight=true"
  force = true

[[redirects]]
  from = "/demo_reports"
  to = "https://app.pansift.com/demo?reports=true"
  force = true

[[redirects]]
  from = "/dl/latest_pkg"
  to = "https://github.com/pansift/p3/raw/main/Pansift-0.6.3.pkg"
  #to = "https://github.com/pansift/p3/raw/main/Pansift-0.6.1.pkg"
  force = true

[[redirects]]
  from = "/terms"
  to = "https://app.pansift.com/terms"
  force = true

[[redirects]]
  from = "/randomtest"
  to = "https://app.pansift.com/"
  force = true
