baseURL = "https://pansift.com"
languageCode = "en-us"
title = "PanSift. Continuous Deterministic Security."
description = "Peace of Mind for Defenders and Developers. Control and detect attackers with continuous high fidelity breach detection."
theme = "navigator-hugo"
summaryLength = 30
enableGitInfo = true

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0

# Site Params
[params]
  description = "Peace of Mind for Defenders and Developers. Control and detect attackers with continuous high fidelity breach detection."
  og_image = "https://pansift.com/images/pansift_social_client_v27.png"
  googleverification = "Um05lPnDDDWPoeNlH_CZ80l6mGzHP0k85-e0fYxY8Z0"
  microsoftverification = "39D63DFF4C2CBD00C9F08F819F62DB65"
  keywords = "infosec, killchain, breach detection, incident response, honeytokens, deception, OWASP, secdevops, devops, nre, sre, network reliability engineering"
    home = "Home"
    logo = "images/mini_header_bnw_v3.png"
    dateFormat = "6 January 2006"
    footerDescription = "Because security can (and should) be black and white."

    # Hero Area Section
    [params.hero]
        enable  = true
        heading = "Peace of Mind for Defenders and Developers. Detect attackers with high fidelity breach detection."
        description = "Nothing is 100% secure. <span style='color: white;'>Breaches are inevitable.</span> Use an attacker's <span style='color: white;'>kill-chain</span> against them as they pivot through your systems. Frictionless install (<span style='color: white;'>30 seconds or less</span>) on any private Github repository. No codebase access requested or required, just automatic honeytokened deploys! Don't leave your organisation or customers exposed for <a href='https://databreachcalculator.mybluemix.net/executive-summary' target='_blank'><span style='color: white; text-decoration: underline;'>279</span></a> days or more..."
        description2 = ""
        button  = true
        btnTxt = "Github Install"
        btnTest = "Low risk test on a personal private repository" 
        btnURL  = "https://github.com/apps/pansift"
        videoThumb = "images/slider/3_steps_v14.png"
        videoURL   = "https://www.youtube.com/embed/I6untRQ8O6U"

    # CVs
    [params.aboutSm]
        enable  = true
        title   = "Because security can and should be <span style = 'color: #000;'>black</span> and <span style = 'color: #fff;'>white</span>."
        subtitle = "Combat F.U.D. with high fidelity and high cardinality breach detection."
 
   # CVs
    [params.faketestimonials]
        topTitle =  "Trust but Verify"
        enable  = true
        title   = "Testimonials?"
        subtitle = "Amidst AI, disinformation, and bots.. <br/> can you spot the human?"
    punchline = "You can even figure out if your team need more security training too!"
        one = "Some attackers are sentient, some are not. None of the humans above exist. They are all AI generated."
        two = "There are critical parts of your systems or applications that no parties should have access to. When honey tokens are tripped it reveals not just the intent but presence of attackers."
        three = "By using honey tokens per deploy, you get <span style='font-size: 1.1em;' class='badge badge-dark mb-2'>high fidelity</span>, and <span style='font-size: 1.1em;' class='badge badge-dark'>high cardinality</span> breach signal."


    # NetDevOps
    [params.netdevops]
        enable  = true
        title   = "NetDevOps, SRE, and NRE skills" 
        subtitle = "De-risk applicants with 'Proof of Experience' labs."

    # Blog Section On Homepage
    [params.blog]
        enable  = true
        topTitle= "What you need to know about hiring"
        title   = "Raise the Bar : Blog"
        subtitle= "Tactics, techniques and procedures for talent teams!"

    # Blog CTA Section On Homepage
    [params.blog_cta]
        enable  = true
        topTitle= ""
        title   = ""
        subtitle= ""

    # Time to Hire Section
    [params.tth]
        enable  = true
        title   = "Time to Hire"
        subtitle= "Reduce your Time to Hire and be confident you don't lose the best candidates"

    # Search Section
    [params.search]
        enable  = true
        title   = "Skill Search"
        subtitle= "Micro test per skill using live cloud simulations."

    # Training Section
    [params.training]
        enable  = true
        title   = "Technical / Security Training"
        subtitle= "With Pluralsight ( inc. 28% off Annual Membership )"

    # Search Section
    [params.cookies]
        enable  = true
        title   = "Cookies"
        subtitle= "Cookie policy"

    # Call to Action Section on About Page
    [params.cta]
        enable  = true
        bg      = "images/call-to-action/cockpit_v3.jpg"
        title   = "Hiring or screening engineers ?"
        subtitle= "Take a quick test flight with 10 free screens."
        btnTxt = "Try it for free"

    # Pricing
    [params.pricing]
        enable  = true
        btnTxt = "Try it for free"


    # Contact Section
    [params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "Contact Us."
        subtitle= ""
        address = "Dublin 5</br> Ireland"
        email   = "info@pansift.com"
        twitter = "https://twitter.com/pansifter"
        linkedin= "https://www.linkedin.com/company/pansift"

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Testimonials"
        url     = "/faketestimonials"
        weight  = 2
    #[[menu.nav]]
    #    name    = "How"
    #    url     = "/howitworks"
    #    weight  = 2
    #[[menu.nav]]
    #    name    = "Why"
    #    url     = "/why"
    #    weight  = 1
    [[menu.nav]]
        name    = "Pricing"
        url     = "/pricing"
        weight  = 1
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 5
    [[menu.nav]]
        name    = "Training"
        url     = "/training"
        weight  = 3
    [[menu.nav]]
        name    = "Talent"
        url     = "/blog"
        weight  = 4
    
    # Footer Quick links Menu
    [[menu.quick]]
        name    = "Pricing"
        url     = "/pricing"
        weight  = 1
    [[menu.quick]]
        name    = "Testimonials"
        url     = "/faketestimonials"
        weight  = 3
    [[menu.quick]]
        name    = "Training"
        url     = "/training"
        weight  = 2
    [[menu.quick]]
        name    = "Contact"
        url     = "/contact"
        weight  = 4

    # Footer About Menu
    [[menu.about]]
        name    = "Team"
        url     = "/team"
        weight  = 1
    [[menu.about]]
        name    = "Cookie Policy"
        url     = "/cookies"
        weight  = 2

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
