baseURL = "https://pansift.com"
languageCode = "en-us"
title = "PanSift: Instant Remote Troubleshooting."
theme = "navigator-hugo"
summaryLength = 37
enableGitInfo = true
# buildDrafts = false


[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
	# smartypants = false

[markup.goldmark.renderer]
unsafe = true

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0

[security.funcs]
	getenv = [ "^HUGO_", "^WC_","^BRANCH" ]

# Site Params + Random Comment
[params]
	description = "Support Work From Anywhere 🌎 with instant remote troubleshooting (Wired and Wi-Fi!) for you, your team, and your clients."
  og_image = "https://pansift.com/images/pansift_social_v38.jpg"
  googleverification = "Um05lPnDDDWPoeNlH_CZ80l6mGzHP0k85-e0fYxY8Z0"
  microsoftverification = "39D63DFF4C2CBD00C9F08F819F62DB65"
  keywords = "digital experience monitoring, wifi assurance, network assurance, future of work, userops, edgeops, incident response, nre, network reliability, sre, site reliability, troubleshooting, wlan, wireless, performance, intermittent issues, defense, network reliability engineering, 802.11, http, synthetic testing, RUM, real user monitoring"
    home = "Home"
    logo = "/images/64.png"
    dateFormat = "6 January 2006"
    footerDescription = ""
    btnTxt = "Instant Demo"
    marketing_tweet = "1189663292312211456"
    marketing_linkedin = "6595640699503288320"

    # Hero Area Section
    [params.hero]
        enable  = true
        bg      = "images/hero/cockpit_inverted_v1.jpg"
				heading = 'Digital Experience Monitoring for Macs 💻 <br>Assure Yourself and Others.'
				# heading = 'Support Work From Anywhere 🌎 Instant remote troubleshooting for forward thinking technical teams.'
        description2 = "Confidently solve current and historical Wi-Fi, DNS, IPv4, IPv6, HTTP, and system issues. Support your team and clients to Work From Anywhere (WFA) 🌎. Instant remote troubleshooting ensures teams stay productive, irrespective of their location!"
				description3 = "See Instant Demo"
        button  = true
        btnTxt = "Early Access"
        btnTest = "" 
        btnURL  = "https://app.pansift.com/demo?first_insight=true"
        videoThumb = "images/slider/3_steps_v15.png"
        videoURL   = "https://www.youtube.com/embed/xxxxxxxxx"

    [params.aboutSm]
        enable  = true
        title   = "Automate your <span style = 'color: #fff;'>troubleshooting</span> and claim back your time!"
        subtitle = "Watch the video to see how to combat support fatigue with instant remote troubleshooting."
        proof = "Gartner forecasts that <strong>~53%</strong> of the UK & US workforce will <u><a target='_blank' href='https://www.gartner.com/en/newsroom/press-releases/2021-06-22-gartner-forecasts-51-percent-of-global-knowledge-workers-will-be-remote-by-2021'>work remotely during 2022</a></u>.<br><strong>DEM (Digital Experience Monitoring)</strong> is the first step to guarantee productivity."
    
		[params.aboutsm2]
        enable  = true
        title   = '<a href="/design"><strong>Simple</strong></a> and <a href="/design"><strong>secure</strong></a> Real User Monitoring for macOS'
		[params.aboutsm3]
        enable  = true
        title   = ' A <a href="/design/"><strong>transparent</strong></a> and <a href="/design/"><strong>trusted</strong></a> time series solution!'

    [params.offer]
        enable  = true
        title   = "<span style = 'color: #fff;'>And PanSift your problems away!</span>"
        subtitle = "Life's too short to fumble around in the dark! Light up your remote workers data path and performance. Claim your time back!"
        description = ""
 
    [params.levelone]
        enable  = true
        title   = "<span style = 'color: #fff;'>Cut Out Hours of Expensive Interactions</span>"
        subtitle = "How much does a level 1 helpdesk, level 2 operator, or level 3 engineer currently cost per hour per remote problem?"

    [params.deception]
        topTitle =  "Trust but Verify"
        enable  = true
        title   = "Deception Tech"
        subtitle = "Amidst AI, disinformation, and bots.. can you spot the human?"
    punchline = "You can even figure out if your team need more security training too!"
        one = "Some attackers are sentient, some are not. None of the humans above exist. They are all AI generated. Separating the signal from the noise is hard."
        two = "There are critical parts of your systems/apps that no external entities should have access to. Tripped honeytokens reveal not just the presence of but the intent of attackers."
        three = "By using honeytokens per pull request (on a deploy branch), you get <span style='font-size: 1.1em;' class='badge badge-dark mb-2'>high fidelity</span>, and <span style='font-size: 1.1em;' class='badge badge-dark'>high cardinality</span> breach signal."

    [params.design]
        enable  = true
        title   = "Design"
        subtitle = "A default multi-tenant architecture, with inspectable client scripts, and outbound only connections."
        sixtitle = "Multitenant Boundaries <br>Enforced Front / Back"
				six = '<a target="_blank" href="https://www.influxdata.com/time-series-platform/telegraf/">Telegraf</a> and <a target="_blank" href="https://www.influxdata.com/time-series-database/">InfluxDB</a> are used for <strong>fail-safe</strong> data ingestion, bucket separation, and storage (with optional <a target="_blank" href="https://docs.influxdata.com/influxdb/cloud/reference/internals/security/">SOC2 Type II cloud</a> vs. OSS).'
        threetitle = "30 Day Data Retention"
        three = "<strong>All agent specific data</strong> is aged out and deleted after <strong>30 days</strong>. Only non-identifiable metrics and aggregate data is used longer term to improve the service."
        fourtitle = "MFA (Multi-factor Authentication)"
        four = 'Use <a target="_blank" href="https://en.wikipedia.org/wiki/Google_Authenticator">Google Authenticator</a>, <a target="_blank" href="https://authy.com/">Authy</a>, or any <a target="_blank" href="https://en.wikipedia.org/wiki/Time-based_one-time_password">TOTP (Time-based One Time Password)</a> generator to secure your account but remember to note your backup codes!'
        fivetitle = "Least Access Principle / BCP NetSec Patterns"
        five = "Agents can only talk <strong>outbound (push)</strong> from your machine. There is <strong>no inbound</strong> communication possible and <strong>no remote access</strong> tooling or functionality. There are <strong>no listening ports</strong> on the agent. It only talks outbound via <strong>DNS and HTTPS TCP 443</strong> to <strong>write</strong> data to (<strong>not read</strong> data from) buckets."
        onetitle = "Apple Signed + Security Scanned"
        one = 'The <strong>agent</strong> is an <a href="https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution">Apple notarized/signed</a> binary which comprises a customized fork of the modular <a target="_blank" href="https://github.com/matryer/xbar">BitBar (now Xbar)</a> agent with OSS <a target="_blank" href="https://github.com/pansift/p3">inspectable scripts</a>.'
        twotitle = "Apple M1 Support"
        two = "The <strong>agent</strong> is cross compiled for both Intel and Apple Silicon (Arm-based) architectures."

    [params.benefits]
        topTitle =  "Trust but Verify"
        enable  = true
        title   = "Stay Connected and Sane"
        subtitle = " Modern business operations are already distributed. Whether cloud based or on-premises, ensure your team stays connected and productive. For everything from <strong>sales demos</strong> and <strong>customer success</strong> calls, to <strong>contact centre (CX)</strong> work and <strong>interviews</strong>, figure out what's going on irrespective of the location (home office, coffee shop, coworking space, main office, etc.)"
        punchline = "Peace of mind in an era of remote work and non-managed networks!"
        onetitle = "Pinpoint Issues Effortlessly, Remotely, and Rapidly"
        one = "Surface wired, <strong>wireless</strong>, and system issues in seconds. Track laptop health for when it's needed most."
        threetitle = "Accelerated Outcomes For Technical Support Teams"
        three = "<strong>Claim back your time</strong> with up to date metrics, anomaly detection, and root cause(s) identification."
        twotitle = "Timetravel with Retrospective Troubleshooting"
        two = "Go back in time to when problems <strong>actually</strong> occurred rather than waiting for them to happen again."
        fourtitle = "Weeks Of Offline Buffering"
        four = "Even when <strong>disconnected</strong>, metrics are buffered and uploaded when reconnected or on hotspots."
        fivetitle = "Added Context From Users"
        five = "<strong>User generated</strong> notes mean more context during any disruptions. The missing link not in any logs!"
        sixtitle = "Super Low Bandwdith"
        six = "Metrics only use a few <strong>kilobits</strong> of bandwidth every 30-60 seconds and almost no CPU."
        seventitle = "Unsurpassed Granularity"
        seven = "High frequency testing (<strong>30s</strong> for most tests) giving the highest fidelity. Non-normalized data means deep debugging!"
        eighttitle = "Synchronous Graphing"
        eight = "Interactive graphs and tabs all <strong>update</strong> when you zoom, pan, tab, or query. Rapidly linked contexts give the whole picture."
        ninetitle = "Real User Monitoring!"
        nine = "IPv4 + IPv6 public/private info, MAC/OUI vendor lookups, WLAN SSID / MCS / rogues, DNS, HTTP(S), system stats etc. All <strong>in-path !</strong>"

    # NetDevOps
    [params.netdevops]
        enable  = true
        title   = "NetDevOps, SRE, and NRE skills" 
        subtitle = "De-risk applicants with 'Proof of Experience' labs."

    # Blog Section On Homepage
    [params.blog]
        enable  = false
        topTitle= "What you need to know about hiring"
        title   = "Raise the Bar : Blog"
        subtitle= "Tactics, techniques and procedures for talent teams!"

    # Blog CTA Section On Homepage
    [params.blog_cta]
        enable  = true
        topTitle= ""
        title   = ""
        subtitle= ""

    # Time to Hire Section
    [params.tth]
        enable  = true
        title   = "Time to Hire"
        subtitle= "Reduce your Time to Hire and be confident you don't lose the best candidates"

    # Search Section
    [params.search]
        enable  = true
        title   = "Skill Search"
        subtitle= "Micro test per skill using live cloud simulations."

    # Training Section
    [params.training]
        enable  = false
        topTitle = "Technical Training"
        title   = "Grow Your Troubleshooting Skills"
        subtitle= "Partner Recommended Courses ( save up to 33% annually )"

    # Search Section
    [params.cookies]
        enable  = true
        title   = "Cookies"
        subtitle= "Cookie policy"

    # Call to Action Section on About Page
    [params.cta]
        enable  = true
        bg      = "images/call-to-action/cockpit_v3.jpg"
        title   = "End user experience monitoring for your team or tribe!"
        subtitle= ""
        btnTxt = "Early Access"

    # Pricing
    [params.pricing]
        enable  = true
        btnTxt = "Try it for free"

    # Early Section
    [params.early]
        enable  = true
        topTitle= "Get Early Access"
        title   = "Be first in the queue!"
        subtitle= ""
    
	# How It Works
    [params.howitworks]
        enable  = true
        topTitle= "Get Early Access"
        title   = "Be first in the queue!"
        subtitle= ""

    # Contact Section
    [params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "Contact Us."
        subtitle= ""
        address = "Dublin 5</br> Ireland"
        email   = "info@pansift.com"
        twitter = "https://twitter.com/pansifter"
        linkedin= "https://www.linkedin.com/company/pansift"

# Site Menus
[menu]
# Navbar Menus
#    [[menu.nav]]
#        name    = "Deception Tech"
#        url     = "/deception/"
#        weight  = 3
#   [[menu.nav]]
#       name    = "Sign Up"
#       url     = "https://app.pansift.com/demo/logout_demo"
#       weight  = 3
#    [[menu.nav]]
#        name    = "Why"
#        url     = "/why/"
#        weight  = 1
#   [[menu.nav]]
#       name    = "How"
#        url     = "/howitworks/"
#        weight  = 1
    [[menu.nav]]
        name    = "Design"
        url     = "/design/"
        weight  = 2
    [[menu.nav]]
        name    = "Pricing"
        url     = "/pricing"
        weight  = 3
#   [[menu.nav]]
#         name    = "Contact"
#         url     = "/contact/"
#         weight  = 1
#   [[menu.nav]]
#       name    = "Benefits"
#       url     = "/benefits/"
#       weight  = 1
#    [[menu.nav]]
#        name    = "Login"
#        url     = "https://app.pansift.com/demo/logout_demo_login"
#        weight  = 6
#    [[menu.nav]]
#        name    = "Sign Up"
#        url     = "/contact/"
#        weight  = 7
    
# Footer Quick links Menu
     [[menu.quick]]
        name    = "Blog"
        url     = "/blog/"
        weight  = 1
    [[menu.quick]]
       name    = "Pricing"
       url     = "/pricing/"
       weight  = 2
    #[[menu.quick]]
    #    name    = "Deception"
    #    url     = "/faketestimonials"
    #    weight  = 3
    [[menu.quick]]
        name    = "Training"
        url     = "/training/"
        weight  = 4
    [[menu.quick]]
        name    = "Contact"
        url     = "/contact/"
        weight  = 3

    # Footer About Menu
    # [[menu.about]]
    #    name    = "Cookie Policy"
    #    url     = "/cookies/"
    #    weight  = 3
    [[menu.about]]
        name    = "Research Topics"
        url     = "/research/"
        weight  = 2
    [[menu.about]]
        name    = "System Status"
        url     = "https://status.pansift.com/"
        weight  = 1

