baseURL = "https://pansift.com"
languageCode = "en-us"
title = "PanSift. Technical recruitment and pre hire assessment testing."
theme = "navigator-hugo"
summaryLength = 30
enableGitInfo = true

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0

# Site Params
[params]
  description = "Just like a pilot is trained and tested in a simulator, PanSift uses simulations to objectively screen applicants or candidates. Hit your hiring targets, save time, and reduce risk for Cloud, Network, and Operations talent."
  og_image = "https://pansift.com/images/pansift_social_client_v23.png"
  googleverification = "Um05lPnDDDWPoeNlH_CZ80l6mGzHP0k85-e0fYxY8Z0"
  microsoftverification = "39D63DFF4C2CBD00C9F08F819F62DB65"
  keywords = "nre, sre, network reliability engineering, netdevops, technical recruitment, pre hire assessment test, skill assessment, skills assessment test, employment assessment test, pre employment assessment, competency based interview, skills testing, hiring assessment test, hiring assessments, router test, pre employment skills testing, employment skills test, employment testing services, new hire assessment tests, online employment testing, hrtech, hiring assessment tools, it technical assessment test, structured interview, admin skills test, employment screening software, job screening process, candidate screening process, pre employment testing software, candidate testing software, structured interview process, employee hiring assessment, scientific hiring, screening as a service, sourcing as a service, structured interview hiring, structured hiring, structured hiring process, take home assessment, job screening software, job screening tools, best job screening questions, automated applicant screening, technical recruitment tools, tech recruiting tools, tool hire recruitment, best new recruiting tools, quantitative aptitude amazon, aptitude test amazon, aptitude test cisco, aptitude test linux, aws skills assessment, free employment tests samples, candidate skills testing, free online competency assessment, employment agency skills test, free employment screening tests, pre employment assessment candidate, applicant testing software, pre employment technical skills, best pre employment testing, online candidate assessment"
    home = "Home"
    logo = "images/mini_header_bnw_v3.png"
    dateFormat = "6 January 2006"
    footerDescription = "The Best Technical Recruitment use a pre hire Assessment Test."

    # Hero Area Section
    [params.hero]
        enable  = true
        heading = "This has been overridden in the page itself"
      description = "Hit your hiring targets, reduce risk, and save time.<br /><br />Just like pilots in a simulator, we use simulations to objectively identify strengths and weaknesses in applicants, candidates, or new hires. Set the bar and screen for technical skills or targeted training."
        button  = true
        btnTxt = "Try it for free"
        btnURL  = "https://client.pansift.com/"
        videoThumb = "images/slider/3_steps_v14.png"
        videoURL   = "https://www.youtube.com/embed/I6untRQ8O6U"

    # CVs
    [params.aboutSm]
        enable  = true
        title   = "CVs and résumés are broken" 
        subtitle = "Use actionable data to make non-biased decisions."

    # NetDevOps
    [params.netdevops]
        enable  = true
        title   = "NetDevOps, SRE, and NRE skills" 
        subtitle = "De-risk applicants with 'Proof of Experience' labs."

    # Blog Section On Homepage
    [params.blog]
        enable  = true
        topTitle= "What you need to know about hiring"
        title   = "Raise the Bar : Blog"
        subtitle= "Tactics, techniques and procedures for talent teams!"

    # Blog CTA Section On Homepage
    [params.blog_cta]
        enable  = true
        topTitle= ""
        title   = ""
        subtitle= ""

    # Time to Hire Section
    [params.tth]
        enable  = true
        title   = "Time to Hire"
        subtitle= "Reduce your Time to Hire and be confident you don't lose the best candidates"

    # Search Section
    [params.search]
        enable  = true
        title   = "Skill Search"
        subtitle= "Micro test per skill using live cloud simulations."

    # Training Section
    [params.training]
        enable  = true
        title   = "Technical Training"
        subtitle= "With Pluralsight ( inc. 28% off Annual Membership )"

    # Search Section
    [params.cookies]
        enable  = true
        title   = "Cookies"
        subtitle= "Cookie policy"

    # Call to Action Section on About Page
    [params.cta]
        enable  = true
        bg      = "images/call-to-action/cockpit_v3.jpg"
        title   = "Hiring or screening engineers ?"
        subtitle= "Take a quick test flight with 10 free screens."
        btnTxt = "Try it for free"

    # Pricing
    [params.pricing]
        enable  = true
        btnTxt = "Try it for free"


    # Contact Section
    [params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "Contact Us."
        subtitle= ""
        address = "Unit 23, Trinity Technology Campus, Dublin 2, Ireland"
        email   = "info@pansift.com"
        twitter = "https://twitter.com/pansifter"
        linkedin= "https://www.linkedin.com/company/pansift"

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Skills"
        url     = "/search"
        weight  = 3
    [[menu.nav]]
        name    = "How"
        url     = "/howitworks"
        weight  = 2
    [[menu.nav]]
        name    = "Why"
        url     = "/why"
        weight  = 1
    [[menu.nav]]
        name    = "Pricing"
        url     = "/pricing"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
    
    # Footer Service Menu
    [[menu.service]]
        name    = "Screening"
        url     = "/howitworks"
        weight  = 1
    [[menu.service]]
        name    = "Training"
        url     = "/training"
        weight  = 2
    [[menu.service]]
        name    = "Blog"
        url     = "/blog"
        weight  = 3

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "Team"
        url     = "/team"
        weight  = 1
    [[menu.quicklink]]
        name    = "Blog Tags"
        url     = "/tags"
        weight  = 2
    [[menu.quicklink]]
        name    = "Contact Us"
        url     = "/contact"
        weight  = 3
    [[menu.quicklink]]
        name    = "Cookie Policy"
        url     = "/cookies"
        weight  = 4

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
