baseURL = "https://pansift.com/"
languageCode = "en-us"
title = "PanSift. Technical recruitment and pre hire assessment test."
theme = "navigator-hugo"
summaryLength = 30

# Site Params
[params]
  description = "Reduce risk, decrease costs, and accelerate Time-to-Hire for Cloud, Infrastructure, and Ops talent. Structured hiring. Technical recruitment pre hire assessment test. Competency based interview. Skills testing. Structured interview. Admin skills test."
  og_image = "/images/pansift_social_client_v21.png"
  googleverification = "Um05lPnDDDWPoeNlH_CZ80l6mGzHP0k85-e0fYxY8Z0"
  microsoftverification = "39D63DFF4C2CBD00C9F08F819F62DB65"
  keywords = "technical recruitment, pre hire assessment test, skill assessment, skills assessment test, employment assessment test, pre employment assessment, competency based interview, skills testing, hiring assessment test, hiring assessments, router test, pre employment skills testing, employment skills test, employment testing services, new hire assessment tests, online employment testing, hrtech, hiring assessment tools, it technical assessment test, structured interview, admin skills test, employment screening software, job screening process, candidate screening process, pre employment testing software, candidate testing software, structured interview process, employee hiring assessment, scientific hiring, screening as a service, sourcing as a service, structured interview hiring, structured hiring, structured hiring process, take home assessment, job screening software, job screening tools, best job screening questions, automated applicant screening, technical recruitment tools, tech recruiting tools, tool hire recruitment, best new recruiting tools, quantitative aptitude amazon, aptitude test amazon, aptitude test cisco, aptitude test linux, aws skills assessment, free employment tests samples, candidate skills testing, free online competency assessment, employment agency skills test, free employment screening tests, pre employment assessment candidate, applicant testing software, pre employment technical skills, best pre employment testing, online candidate assessment"
    home = "Home"
    logo = "images/mini_header_bnw_v3.png"
    dateFormat = "6 January 2006"
    footerDescription = "The Best Technical Recruitment use a pre hire Assessment Test."

    # Hero Area Section
    [params.hero]
        enable  = true
        heading = "The Best Technical Recruitment use a pre hire Assessment Test."
        description = "Reduce risk, decrease costs, and accelerate Time-to-Hire for Cloud, Infrastructure, and Ops talent."

        button  = true
        btnText = "Free Sign Up"
        btnURL  = "https://client.pansift.com/"
        videoThumb = "images/slider/3_steps_v14.png"
        videoURL   = "https://www.youtube.com/embed/I6untRQ8O6U"

    # About 2 Section
    [params.aboutSm]
        enable  = true
        title   = "CVs are biased and broken." 
        subtitle = "Use actionable data to support decision making throughout the hiring funnel."

    # Blog Section On Homepage
    [params.blog]
        enable  = true
        topTitle= "What you need to know about hiring"
        title   = "Raise the Bar : Blog"
        subtitle= "Tactics, techniques and procedures for keeping pace with modern technology!"

    # Blog CTA Section On Homepage
    [params.blog_cta]
        enable  = true
        topTitle= ""
        title   = ""
        subtitle= ""

    # Time to Hire Section
    [params.tth]
        enable  = true
        title   = "Time to Hire"
        subtitle= "Reduce your Time to Hire and be confident you don't lose the best candidates"

    # Search Section
    [params.search]
        enable  = true
        title   = "Search PanSift Technical Skills"
        subtitle= "Improve your job screening process with testable skills and automated applicant screening"

    # Search Section
    [params.training]
        enable  = true
        title   = "Technical Training"
        subtitle= "Featured Pluralsight training ( inc. 15% off Annual Subscriptions )"

    # Search Section
    [params.cookies]
        enable  = true
        title   = "Cookies"
        subtitle= "Cookie policy"

    # Call to Action Section on About Page
    [params.cta]
        enable  = true
        bg      = "images/call-to-action/cockpit_v3.jpg"
        title   = "Engineering or hiring leader ?"
        subtitle= "Take a quick test flight with 10 free screens."
        btnText = "Get Started Free"

    # Contact Section
    [params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "Contact Us."
        subtitle= "Reduce risk, decrease costs, and accelerate Time-to-Hire for Cloud, Infrastructure, and Ops talent. Structured hiring."
        address = "Unit 23, Trinity Technology & Enterprise Campus, Dublin 2, D02WR66, Ireland"
        email   = "info@pansift.com"
        twitter = "https://twitter.com/pansifter"
        linkedin= "https://www.linkedin.com/company/pansift"

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "How It Works"
        url     = "/howitworks"
        weight  = 1
    [[menu.nav]]
        name    = "Why"
        url     = "/why"
        weight  = 2
    [[menu.nav]]
        name    = "Pricing"
        url     = "/pricing"
        weight  = 3
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 4
    [[menu.nav]]
        name    = "Login"
        url     = "https://client.pansift.com/clients/sign_in"
        weight  = 5
    
    # Footer Service Menu
    [[menu.service]]
        name    = "Blog"
        url     = "/blog"
        weight  = 1
    [[menu.service]]
        name    = "Training"
        url     = "/training"
        weight  = 2

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "Pricing"
        url     = "/pricing"
        weight  = 3
    [[menu.quicklink]]
        name    = "Search"
        url     = "/search"
        weight  = 2
    [[menu.quicklink]]
        name    = "Team"
        url     = "/team"
        weight  = 4
    [[menu.quicklink]]
        name    = "Contact Us"
        url     = "/contact"
        weight  = 1
    [[menu.quicklink]]
        name    = "Cookie Policy"
        url     = "/cookies"
        weight  = 5

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
