baseURL = "https://pansift.com"
languageCode = "en-us"
title = "PanSift for a rapid find and fix."
theme = "navigator-hugo"
summaryLength = 37
enableGitInfo = true

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0

[markup.goldmark.renderer]
unsafe = true

# Site Params
[params]
	description = "Instant remote troubleshooting for forward thinking technical teams. Embrace work from anywhere. Regain control of time and fix Wifi, ISP, DNS and laptop issues in moments."
  og_image = "https://pansift.com/images/pansift_social_v37.jpg"
  googleverification = "Um05lPnDDDWPoeNlH_CZ80l6mGzHP0k85-e0fYxY8Z0"
  microsoftverification = "39D63DFF4C2CBD00C9F08F819F62DB65"
  keywords = "wifi assurance, network assurance, future of work, userops, edgeops, incident response, nre, network reliability, sre, site reliability, troubleshooting, wlan, wireless, performance, intermittent issues, defense, network reliability engineering, 802.11, http, synthetic testing, RUM, real user monitoring"
    home = "Home"
    logo = "images/mini_header_bnw_v3.png"
    dateFormat = "6 January 2006"
    footerDescription = ""
    btnTxt = "One-Click Demo"
    marketing_tweet = "1189663292312211456"
    marketing_linkedin = "6595640699503288320"

    # Hero Area Section
    [params.hero]
        enable  = true
				heading = "Instant remote troubleshooting for forward thinking technical teams. P.S. Embrace work from anywhere."
        description2 = "Support users and clients who <span style='color: white;'>Work From Anywhere (WFA)</span> by solving Wi-Fi, network (IPv4 + IPv6), and system issues <span style='color: white;'>rapidly</span>. Accelerate Time to Resolution and go from WTF to WFA 😎 starting with <u><a href='/pricing' style='color: white;'><strong>2 x free agents</strong></a></u>" 
        button  = true
        btnTxt = "Early Access"
        btnTest = "" 
        btnURL  = "https://app.pansift.com/demo"
        videoThumb = "images/slider/3_steps_v15.png"
        videoURL   = "https://www.youtube.com/embed/xxxxxxxxx"

    [params.aboutSm]
        enable  = true
        title   = "Troubleshooting can and should be <span style = 'color: #000;'>black</span> and <span style = 'color: #fff;'>white</span>."
        subtitle = "Combat support fatigue with high fidelity automated troubleshooting."
        proof = "Gartner <u><a target='_blank' href='https://www.gartner.com/en/newsroom/press-releases/2021-06-22-gartner-forecasts-51-percent-of-global-knowledge-workers-will-be-remote-by-2021'>forecasts</a></u> that <strong>~53%</strong> of the UK & US workforce will work remotely during 2022, with <strong>31%</strong> globally."

    [params.offer]
        enable  = true
        title   = "<span style = 'color: #fff;'>PanSift your Problems!</span>"
        subtitle = "Life's too short to fumble around in the dark! Light up your remote workers data path and performance. Claim your time back!"
        description = ""
 
    [params.deception]
        topTitle =  "Trust but Verify"
        enable  = true
        title   = "Deception Tech"
        subtitle = "Amidst AI, disinformation, and bots.. can you spot the human?"
    punchline = "You can even figure out if your team need more security training too!"
        one = "Some attackers are sentient, some are not. None of the humans above exist. They are all AI generated. Separating the signal from the noise is hard."
        two = "There are critical parts of your systems/apps that no external entities should have access to. Tripped honeytokens reveal not just the presence of but the intent of attackers."
        three = "By using honeytokens per pull request (on a deploy branch), you get <span style='font-size: 1.1em;' class='badge badge-dark mb-2'>high fidelity</span>, and <span style='font-size: 1.1em;' class='badge badge-dark'>high cardinality</span> breach signal."

    [params.benefits]
        topTitle =  "Trust but Verify"
        enable  = true
        title   = "Support Work From Anywhere"
        subtitle = "It's not just <strong>sales demos</strong>, <strong>customer success calls</strong>, or <strong>interviews</strong> that are performed remotely but every aspect of modern business operations can and are distributed. Ensure you can solve issues rapidly and remotely so teams can stay connected and productive."
        punchline = "Peace of mind in an era of remote work and non-managed networks!<br>Get your time and sanity back irrespective of where you are and who you are helping."
        onetitle = "Pinpoint Issues Effortlessly, Remotely, and Rapidly"
        one = "Surface wired, <strong>wireless</strong>, and system issues in seconds. Track laptop health for when it's needed most."
        threetitle = "Accelerated Outcomes For Technical Support Teams"
        three = "<strong>Claim back your time</strong> with up to date metrics, anomaly detection, and root cause(s) identification."
        twotitle = "Timetravel with Retrospective Troubleshooting"
        two = "Go back in time to when problems <strong>actually</strong> occurred rather than waiting for them to happen again."
        fourtitle = "Weeks Of Offline Buffering"
        four = "Even when <strong>disconnected</strong>, metrics are buffered and uploaded when reconnected or on hotspots."
        fivetitle = "Added Context From Users"
        five = "Elective <strong>user annotations</strong> mean more context during any disruptions. The missing link not in any logs!"
        sixtitle = "Super Low Bandwdith"
        six = "Metrics only use a few <strong>kilobits</strong> of bandwidth every 30-60 seconds and almost no CPU."
        seventitle = "Unsurpassed Granularity"
        seven = "High frequency testing (<strong>30s</strong> for most tests) giving the highest fidelity. Non-normalized data means deep debugging!"
        eighttitle = "Synchronous Graphing"
        eight = "Interactive graphs and tabs all <strong>update</strong> when you zoom, pan, tab, or query. Rapidly linked contexts give the whole picture."
        ninetitle = "Real User Monitoring!"
        nine = "IPv4 + IPv6 public/private info, MAC/OUI vendor lookups, WLAN SSID / MCS / rogues, DNS, HTTP(S), system stats etc. All <strong>in-path !</strong>"

    # NetDevOps
    [params.netdevops]
        enable  = true
        title   = "NetDevOps, SRE, and NRE skills" 
        subtitle = "De-risk applicants with 'Proof of Experience' labs."

    # Blog Section On Homepage
    [params.blog]
        enable  = false
        topTitle= "What you need to know about hiring"
        title   = "Raise the Bar : Blog"
        subtitle= "Tactics, techniques and procedures for talent teams!"

    # Blog CTA Section On Homepage
    [params.blog_cta]
        enable  = true
        topTitle= ""
        title   = ""
        subtitle= ""

    # Time to Hire Section
    [params.tth]
        enable  = true
        title   = "Time to Hire"
        subtitle= "Reduce your Time to Hire and be confident you don't lose the best candidates"

    # Search Section
    [params.search]
        enable  = true
        title   = "Skill Search"
        subtitle= "Micro test per skill using live cloud simulations."

    # Training Section
    [params.training]
        enable  = false
        topTitle = "Technical Training"
        title   = "Grow Your Troubleshooting Skills"
        subtitle= "Partner Recommended Courses ( save up to 33% annually )"

    # Search Section
    [params.cookies]
        enable  = true
        title   = "Cookies"
        subtitle= "Cookie policy"

    # Call to Action Section on About Page
    [params.cta]
        enable  = true
        bg      = "images/call-to-action/cockpit_v3.jpg"
        title   = "Monitor, find, and fix issues for your team, tribe, or family."
        subtitle= ""
        btnTxt = "Early Access"

    # Pricing
    [params.pricing]
        enable  = true
        btnTxt = "Try it for free"

    # Early Section
    [params.early]
        enable  = true
        topTitle= "Get Early Access"
        title   = "Be first in the queue!"
        subtitle= ""
    
	# How It Works
    [params.howitworks]
        enable  = true
        topTitle= "Get Early Access"
        title   = "Be first in the queue!"
        subtitle= ""

    # Contact Section
    [params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "Contact Us."
        subtitle= ""
        address = "Dublin 5</br> Ireland"
        email   = "info@pansift.com"
        twitter = "https://twitter.com/pansifter"
        linkedin= "https://www.linkedin.com/company/pansift"

# Site Menus
[menu]
# Navbar Menus
#    [[menu.nav]]
#        name    = "Deception Tech"
#        url     = "/deception"
#        weight  = 3
#   [[menu.nav]]
#       name    = "Sign Up"
#       url     = "https://app.pansift.com/demo/logout_demo"
#       weight  = 3
#    [[menu.nav]]
#        name    = "Why"
#        url     = "/why"
#        weight  = 1
    [[menu.nav]]
        name    = "Pricing"
        url     = "/pricing"
        weight  = 1
#   [[menu.nav]]
#         name    = "Contact"
#         url     = "/contact"
#         weight  = 1
#    [[menu.nav]]
#        name    = "Blog"
#        url     = "/blog"
#        weight  = 2
#   [[menu.nav]]
#       name    = "Benefits"
#       url     = "/benefits"
#       weight  = 1
#    [[menu.nav]]
#        name    = "Login"
#        url     = "/contact"
#        weight  = 6
#    [[menu.nav]]
#        name    = "Sign Up"
#        url     = "/contact"
#        weight  = 7
    
# Footer Quick links Menu
     [[menu.quick]]
        name    = "Blog"
        url     = "/blog"
        weight  = 1
    [[menu.quick]]
       name    = "Pricing"
       url     = "/pricing"
       weight  = 2
    #[[menu.quick]]
    #    name    = "Deception"
    #    url     = "/faketestimonials"
    #    weight  = 3
    [[menu.quick]]
        name    = "Training"
        url     = "/training"
        weight  = 4
    [[menu.quick]]
        name    = "Contact"
        url     = "/contact"
        weight  = 3

    # Footer About Menu
    [[menu.about]]
        name    = "Cookie Policy"
        url     = "/cookies"
        weight  = 2

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
