[[redirects]]
from = "https://master--panland.netlify.com/*"
to = "https://pansift/:splat"
status = 302
force = true

[[redirects]]
from = "/why*"
to = "https://pansift/:splat"
status = 302
force = true

[[redirects]]
from = "/simulate*"
to = "https://pansift/:splat"
status = 302
force = true
